#!/usr/bin/env bash
# Regenerate the Copilot-facing mirror of skills from the canonical Claude Code copy.
#
# `.claude/skills/` is AUTHORED. `.github/skills/` is a GENERATED byte-identical mirror so that
# GitHub Copilot CLI and the Copilot cloud agent (which read `.github/skills/`) see the same
# recipes Claude Code reads from `.claude/skills/`. VS Code Copilot already reads `.claude/skills/`
# directly, so the mirror is for the CLI / cloud-agent surfaces.
#
# Run this after adding, editing, or removing a skill. `/generate-copilot` runs it for you;
# the docs-sync CI check fails if the mirror is out of date.
set -euo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$root"

src=".claude/skills"
dst=".github/skills"

if [ ! -d "$src" ]; then
  echo "No $src directory — nothing to sync."
  exit 0
fi

rm -rf "$dst"
mkdir -p "$dst"
cp -r "$src/." "$dst/"

count=$(find "$dst" -name SKILL.md 2>/dev/null | wc -l | tr -d ' ')
echo "Synced $count skill(s): $src -> $dst"
