# Regenerate the Copilot-facing mirror of skills from the canonical Claude Code copy.
#
# `.claude/skills/` is AUTHORED. `.github/skills/` is a GENERATED byte-identical mirror so that
# GitHub Copilot CLI and the Copilot cloud agent (which read `.github\skills\`) see the same
# recipes Claude Code reads from `.claude\skills\`. VS Code Copilot already reads `.claude\skills\`
# directly, so the mirror is for the CLI / cloud-agent surfaces.
#
# Run this after adding, editing, or removing a skill. `/generate-copilot` runs it for you;
# the docs-sync CI check fails if the mirror is out of date.
$ErrorActionPreference = 'Stop'

$root = (git rev-parse --show-toplevel 2>$null)
if (-not $root) { $root = (Get-Location).Path }
Set-Location $root

$src = '.claude/skills'
$dst = '.github/skills'

if (-not (Test-Path $src)) {
    Write-Output "No $src directory -- nothing to sync."
    exit 0
}

if (Test-Path $dst) { Remove-Item -Recurse -Force $dst }
New-Item -ItemType Directory -Force -Path $dst | Out-Null
Copy-Item -Recurse -Force (Join-Path $src '*') $dst

$count = (Get-ChildItem -Recurse -Filter SKILL.md $dst | Measure-Object).Count
Write-Output "Synced $count skill(s): $src -> $dst"
